version: '3.5'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: bryro-grafana
    ports:
      - '3000:3000'
    networks:
      - bryro-network
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD} 
volumes:
  grafana-storage:
networks:
  bryro-network:
    name: bryro-network
    driver: bridge
